# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import schedule_pb2 as schedule__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetScheduleByDate = channel.unary_unary(
                '/Schedule/GetScheduleByDate',
                request_serializer=schedule__pb2.Date.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleData.FromString,
                _registered_method=True)
        self.GetAllScheduleDays = channel.unary_unary(
                '/Schedule/GetAllScheduleDays',
                request_serializer=schedule__pb2.Empty.SerializeToString,
                response_deserializer=schedule__pb2.Planning.FromString,
                _registered_method=True)
        self.AddScheduleDay = channel.unary_unary(
                '/Schedule/AddScheduleDay',
                request_serializer=schedule__pb2.ScheduleData.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleData.FromString,
                _registered_method=True)
        self.DeleteScheduleDay = channel.unary_unary(
                '/Schedule/DeleteScheduleDay',
                request_serializer=schedule__pb2.Date.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleData.FromString,
                _registered_method=True)


class ScheduleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetScheduleByDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllScheduleDays(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddScheduleDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScheduleDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetScheduleByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleByDate,
                    request_deserializer=schedule__pb2.Date.FromString,
                    response_serializer=schedule__pb2.ScheduleData.SerializeToString,
            ),
            'GetAllScheduleDays': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllScheduleDays,
                    request_deserializer=schedule__pb2.Empty.FromString,
                    response_serializer=schedule__pb2.Planning.SerializeToString,
            ),
            'AddScheduleDay': grpc.unary_unary_rpc_method_handler(
                    servicer.AddScheduleDay,
                    request_deserializer=schedule__pb2.ScheduleData.FromString,
                    response_serializer=schedule__pb2.ScheduleData.SerializeToString,
            ),
            'DeleteScheduleDay': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScheduleDay,
                    request_deserializer=schedule__pb2.Date.FromString,
                    response_serializer=schedule__pb2.ScheduleData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Schedule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Schedule', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Schedule(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetScheduleByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/GetScheduleByDate',
            schedule__pb2.Date.SerializeToString,
            schedule__pb2.ScheduleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllScheduleDays(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/GetAllScheduleDays',
            schedule__pb2.Empty.SerializeToString,
            schedule__pb2.Planning.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddScheduleDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/AddScheduleDay',
            schedule__pb2.ScheduleData.SerializeToString,
            schedule__pb2.ScheduleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteScheduleDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/DeleteScheduleDay',
            schedule__pb2.Date.SerializeToString,
            schedule__pb2.ScheduleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
